### ISSUE TITLE
Can't get move-shards or remove-node to work on Couch 3

### ISSUE THREAD

**Issue by Hareet** [medic/couchdb-migration#21]
I'm trying to cluster an echis (cht-core 4.9, couchdb3) project from single node to multi node.

Can you clarify how getUrl  that calls [preparedCouchUrl](https://github.com/medic/couchdb-migration/blob/main/src/utils.js#L57) is populating and returning var couchClusterUrl in utils? 

I'm suspecting that `/_node/_local/` is not getting sent to latter functions like [getDbs](https://github.com/medic/couchdb-migration/blob/main/src/utils.js#L117) and [updateDbMetadata](https://github.com/medic/couchdb-migration/blob/main/src/utils.js#L157)

Specifically, in couchdb 3.x , getDbs needs to use getUrl without the additional `/_node/_local`, such that `_all_dbs` is at root endpoint (`http://medic:pw@couchdb-1-host:5984/_all_dbs`). Then when updateDbMetadata calls getUrl, it needs to add `/_node/_local/` before it iterates on each db that it retrieved, otherwise I believe we are running into our current error:

```
Error while getting database metadata
An unexpected error occurred HTTPResponseError: HTTP Error Response: 404 Object Not Found
    at request (/app/src/utils.js:110:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.getDbMetadata (/app/src/utils.js:142:12)
    at async moveShard (/app/src/move-shard.js:49:22)
    at async /app/bin/move-shards.js:10:7 {
  response: { error: 'not_found', reason: 'Database does not exist.' },
  status: 404
}
```

When I ran `remove-node`, it gave further evidence that the additional `/_node/_local` was missing:
```
Error while getting node info HTTPResponseError: HTTP Error Response: 404 Object Not Found
    at request (/app/src/utils.js:110:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.getNodeInfo (/app/src/utils.js:173:12)
    at async removeNode (/app/src/remove-node.js:11:20)
    at async /app/bin/remove-node.js:8:5 {
  response: { error: 'not_found', reason: 'Database does not exist.' },
  status: 404
}
An unexpected error occurred Error: Error while getting node info
    at Object.getNodeInfo (/app/src/utils.js:176:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async removeNode (/app/src/remove-node.js:11:20)
    at async /app/bin/remove-node.js:8:5
```
getNodeInfo runs into the same issue.

I'm able to remove the node by finding the rev-id and hitting `_nodes` directly.

When running [move-shards](https://github.com/medic/couchdb-migration/blob/main/src/move-shard.js#L49) and getting the first error that was pasted above as output, I'm able to curl that db:
```
root@af:/# curl http://medic:pw@couchdb-1.test.svc.cluster.local:5984/_dbs/medic-users-meta
{"error":"not_found","reason":"Database does not exist."}

root@af:/# curl http://medic:pw@couchdb-1.test:5984/_node/_local/_dbs/medic-users-meta
{"_id":"medic-users-meta","_rev":"13-f6a89db990","shard_suffix":[46,49,54,56,50,57,53,54,55,57,56],"changelog"
....
```

Am I missing something that forces couch-migration to prepare couch-3 urls inside the compose file I'm using for this repo?
```
migration.yml

version: '3.9'

services:
  couch-migration:
    image: public.ecr.aws/medic/couchdb-migration:1.0.3
    networks:
      - cht-net
    environment:
      - "COUCH_URL=http://medic:pw@couchdb-1.test.local:5984"
      - "COUCH_CLUSTER_PORT=5984"

networks:
  cht-net:
    name: ${CHT_NETWORK:-cht-net}
    external: true
```

**Comment by Hareet** [comment]
here's `/_membership` from couchdb-2:
```
root@af:/# curl http://medic:pw@couchdb-2.test.svc.cluster.local:5984/_membership
{"all_nodes":["couchdb@couchdb-1.test.svc.cluster.local","couchdb@couchdb-2.test.svc.cluster.local","couchdb@couchdb-3.test.svc.cluster.local"],"cluster_nodes":["couchdb@couchdb-1.test.svc.cluster.local","couchdb@couchdb-2.test.svc.cluster.local","couchdb@couchdb-3.test.svc.cluster.local"]}

**Comment by Hareet** [comment]
Now, I'm confused as to how move-shards worked when renaming couchdb@127.0.0.1 to single-node couchdb@couchdb-1.test-echis.svc.cluster.local?
```
investigator@echisiclone:~/cht$ echo "$shard_matrix"
{
  "00000000-15555554": "couchdb@couchdb-1.test-echis.svc.cluster.local",
  "15555555-2aaaaaa9": "couchdb@couchdb-1.test-echis.svc.cluster.local",
  "2aaaaaaa-3ffffffe": "couchdb@couchdb-1.test-echis.svc.cluster.local",
  "3fffffff-55555553": "couchdb@couchdb-1.test-echis.svc.cluster.local",
  "55555554-6aaaaaa8": "couchdb@couchdb-1.test-echissvc.cluster.local",
  "6aaaaaa9-7ffffffd": "couchdb@couchdb-1.test-echissvc.cluster.local",
  "7ffffffe-95555552": "couchdb@couchdb-1.test-echis.svc.cluster.local",
  "95555553-aaaaaaa7": "couchdb@couchdb-1.test-echis.svc.cluster.local",
  "aaaaaaa8-bffffffc": "couchdb@couchdb-1.test-echis.svc.cluster.local",
  "bffffffd-d5555551": "couchdb@couchdb-1.test-echis.svc.cluster.local",
  "d5555552-eaaaaaa6": "couchdb@couchdb-1.test-echis.svc.cluster.local",
  "eaaaaaa7-ffffffff": "couchdb@couchdb-1.test-echis.svc.cluster.local"
}
For that shard_matrix, this worked:

sudo shard_matrix="$shard_matrix" docker compose -f migration.yml run couch-migration move-shards "$shard_matrix"

But now, when running with a shard-map:
investigator@echisiclone:~/cht$ echo "$shard_matrix"
{
  "00000000-15555554": "couchdb@couchdb-1.test-echis.svc.cluster.local",
  "15555555-2aaaaaa9": "couchdb@couchdb-2.test-echis.svc.cluster.local",
  "2aaaaaaa-3ffffffe": "couchdb@couchdb-3.test-echis.svc.cluster.local",
  "3fffffff-55555553": "couchdb@couchdb-1.test-echis.svc.cluster.local",
  "55555554-6aaaaaa8": "couchdb@couchdb-2.test-echissvc.cluster.local",
  "6aaaaaa9-7ffffffd": "couchdb@couchdb-3.test-echissvc.cluster.local",
  "7ffffffe-95555552": "couchdb@couchdb-1.test-echis.svc.cluster.local",
  "95555553-aaaaaaa7": "couchdb@couchdb-2.test-echis.svc.cluster.local",
  "aaaaaaa8-bffffffc": "couchdb@couchdb-3.test-echis.svc.cluster.local",
  "bffffffd-d5555551": "couchdb@couchdb-1.test-echis.svc.cluster.local",
  "d5555552-eaaaaaa6": "couchdb@couchdb-2.test-echis.svc.cluster.local",
  "eaaaaaa7-ffffffff": "couchdb@couchdb-3.test-echis.svc.cluster.local"
}
 We get the errors that I discussed in the ticket.
 
Nothing I've changed in migration.yml (docker compose template that contains couchdb-migration declaration).
So I'm at a loss as to why move-shards is now not using couch3 urls?
```

**Comment by dianabarsan** [comment]
Hi @Hareet 

Can you make sure you are using the latest version of the migration script? We added support for Couch3 in version 1.0.2.

**Comment by dianabarsan** [comment]
We should have support for Couch3 out of the box, added in v 1.0.2. We have e2e tests which move shards in Couch3. 

Can you check the logs in the migration container to see how the error looks like?

**Comment by dianabarsan** [comment]
It looks like the CouchDb 3 detection script gets confused when the `COUCH_CLUSTER_PORT` is set as 5984. The way it works is it goes by process of elimination, but when the clustering port is set to 5984, one of the Couch2 urls that it tests responds. So the migration script thinks it's couch2 it is migrating. 

Either not setting the COUCH_CLUSTER_PORT or setting it to `COUCH_CLUSTER_PORT` should fix it.
I'll either document this or change the detection to be bespoke.
